# SD212: Graph mining

# Sparse matrices

The objective of this lab is to learn to work with sparse matrices.

In [1]:
import numpy as np
from scipy import sparse

## CSR format

We first focus on the [CSR](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html)  (Compressed Sparse Row) format. Note that there is the [CSC](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html) (Compressed Sparse Column) format, which is nothing but the CSR format of the transpose matrix.

In [2]:
# random matrix (dense format)
X_dense = np.random.randint(3, size = (10,5))

In [3]:
X_dense

array([[1, 2, 1, 2, 1],
       [1, 1, 0, 0, 1],
       [0, 0, 2, 0, 1],
       [2, 2, 2, 0, 2],
       [1, 0, 0, 2, 0],
       [2, 2, 0, 0, 0],
       [2, 1, 2, 0, 2],
       [0, 2, 1, 0, 0],
       [2, 2, 2, 0, 1],
       [2, 1, 1, 1, 0]])

In [4]:
X_csr = sparse.csr_matrix(X_dense)

In [5]:
X_csr.shape

(10, 5)

In [6]:
X_csr.nnz

32

The data structure consists of 3 vectors:

In [7]:
X_csr.indices

array([0, 1, 2, 3, 4, 0, 1, 4, 2, 4, 0, 1, 2, 4, 0, 3, 0, 1, 0, 1, 2, 4,
       1, 2, 0, 1, 2, 4, 0, 1, 2, 3])

In [8]:
X_csr.indptr

array([ 0,  5,  8, 10, 14, 16, 18, 22, 24, 28, 32])

In [9]:
X_csr.data

array([1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2,
       2, 1, 2, 2, 2, 1, 2, 1, 1, 1], dtype=int32)

## To do

Can you find the number of non-zeros ``nnz`` and the shape of the matrix from these vectors?

In [12]:
print(len(X_csr.data))
print(len(X_csr.indptr)-1, max(X_csr.indices)+1)


32
10 5


## Arithmetic

Usual arithmetic operations apply to sparse matrices. The only contraint is to have the sparse matrix on the left-hand side of the operator.

In [13]:
n_row, n_col = 10, 4
X_dense = np.random.randint(2, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [14]:
X_dense

array([[0, 1, 1, 1],
       [0, 0, 1, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 1, 1, 1],
       [0, 1, 1, 0],
       [1, 0, 1, 0],
       [1, 1, 1, 0]])

In [15]:
a = np.ones(n_col, dtype=int)

In [16]:
b = X.dot(a)

In [17]:
b

array([3, 2, 1, 0, 1, 1, 4, 2, 2, 3], dtype=int32)

In [18]:
a = np.ones(n_row, dtype=int)
b = X.T.dot(a)

In [19]:
b

array([4, 4, 8, 3], dtype=int32)

In [20]:
A = np.random.randint(2, size=(n_col, 2))
B = X.dot(A)

In [21]:
A

array([[0, 1],
       [0, 1],
       [1, 0],
       [1, 0]])

In [22]:
B

array([[2, 1],
       [2, 0],
       [0, 1],
       [0, 0],
       [1, 0],
       [1, 0],
       [2, 2],
       [1, 1],
       [1, 1],
       [1, 2]], dtype=int32)

In [23]:
A = sparse.csr_matrix(A)
B = X.dot(A)

In [24]:
B

<10x2 sparse matrix of type '<class 'numpy.intc'>'
	with 14 stored elements in Compressed Sparse Row format>

In [25]:
B.toarray()

array([[2, 1],
       [2, 0],
       [0, 1],
       [0, 0],
       [1, 0],
       [1, 0],
       [2, 2],
       [1, 1],
       [1, 1],
       [1, 2]], dtype=int32)

In [26]:
X.T.dot(X)

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 16 stored elements in Compressed Sparse Column format>

In [27]:
X.dot(X.T)

<10x10 sparse matrix of type '<class 'numpy.intc'>'
	with 71 stored elements in Compressed Sparse Row format>

In [28]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [29]:
X

<10x5 sparse matrix of type '<class 'numpy.intc'>'
	with 33 stored elements in Compressed Sparse Row format>

In [30]:
Y = X > 1

In [31]:
Y

<10x5 sparse matrix of type '<class 'numpy.bool_'>'
	with 17 stored elements in Compressed Sparse Row format>

In [32]:
Y.dot(np.ones(n_col, dtype=int))

array([2, 0, 4, 3, 1, 1, 0, 2, 3, 1], dtype=int32)

In [33]:
Y.dot(np.ones(n_col, dtype=bool))

array([ True, False,  True,  True,  True,  True, False,  True,  True,
        True])

In [34]:
Z = 2 * X + 5 * Y

In [35]:
Z

<10x5 sparse matrix of type '<class 'numpy.intc'>'
	with 33 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [36]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Compute the vector of the Euclidean norm of each row.

In [37]:
prod = X.dot(X.T)
diag = prod.diagonal()
norm = np.sqrt(diag)

norm

array([2.23606798, 3.        , 2.44948974, 2.44948974, 2.23606798,
       2.23606798, 2.23606798, 3.16227766, 3.60555128, 2.44948974,
       1.41421356, 3.16227766, 2.44948974, 1.        , 1.41421356,
       3.        , 2.23606798, 2.82842712, 1.73205081, 3.        ])

## Slicing

Sparse matrices can be sliced like numpy arrays.

In [40]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))

In [41]:
X = sparse.csr_matrix(X_dense)

In [42]:
indices = [2, 5, 6]

In [43]:
X[indices]

<3x5 sparse matrix of type '<class 'numpy.intc'>'
	with 10 stored elements in Compressed Sparse Row format>

In [44]:
X[:, [1, 3]]

<10x2 sparse matrix of type '<class 'numpy.intc'>'
	with 15 stored elements in Compressed Sparse Row format>

## To do 

Consider the following matrix:

In [45]:
n_row, n_col = 20, 10
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Select the 5 rows of largest sums and build the corresponding CSR matrix (size 5 x 10).

In [46]:
sum = X.dot(np.ones(n_col))
print(sum)

indices = np.argsort(sum)[-5:]
print(indices)

Y = X[indices]
Y

[ 7.  9. 10. 10.  7. 12.  9. 14. 14.  8.  8.  9.  9. 11.  9. 13.  7. 10.
 13. 10.]
[ 5 18 15  7  8]


<5x10 sparse matrix of type '<class 'numpy.intc'>'
	with 44 stored elements in Compressed Sparse Row format>

## DIAG format

In [47]:
D = sparse.diags(np.arange(10))

In [48]:
D

<10x10 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements (1 diagonals) in DIAgonal format>

In [49]:
D.data

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [50]:
D.nnz

10

In [51]:
D = sparse.csr_matrix(D)

In [52]:
D.data

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [53]:
D.nnz

9

In [54]:
n_row, n_col = 10, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

In [55]:
D.dot(X)

<10x4 sparse matrix of type '<class 'numpy.float64'>'
	with 15 stored elements in Compressed Sparse Row format>

In [56]:
D = sparse.diags(np.ones(4))

In [58]:
X.dot(D)

<10x4 sparse matrix of type '<class 'numpy.float64'>'
	with 18 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [59]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

Using sparse diagonal matrices:
* Normalize this matrix so that each row sums to 1 (or to 0 if the whole row is zero). 

In [60]:
X.data = X.data.astype(float)

sum = X.dot(np.ones(n_col, dtype=float))
print(sum)

for i in range(n_row):
    if sum[i] != 0:
        X.data[X.indptr[i]: X.indptr[i+1]] /= sum[i]

X.data

[2. 4. 2. 2. 3. 1. 1. 2. 2. 1. 2. 0. 3. 3. 2. 3. 2. 4. 1. 2.]


array([0.5       , 0.5       , 0.25      , 0.25      , 0.25      ,
       0.25      , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.33333333, 0.33333333, 0.33333333, 1.        , 1.        ,
       0.5       , 0.5       , 0.5       , 0.5       , 1.        ,
       0.5       , 0.5       , 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.5       , 0.5       ,
       0.33333333, 0.33333333, 0.33333333, 0.5       , 0.5       ,
       0.25      , 0.25      , 0.25      , 0.25      , 1.        ,
       0.5       , 0.5       ])

## COO format

Another way to represent sparse matrices is the COO (COOrdinate) format. It is useful to load a matrix from a list of entries.

In [61]:
row = [1, 4, 2]
col = [2, 0, 2]
data = [1, 2, 3]

In [62]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [63]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in COOrdinate format>

In [64]:
X_coo.row

array([1, 4, 2])

In [65]:
X_coo.col

array([2, 0, 2])

In [66]:
X_coo.data

array([1, 2, 3])

You can change the format:

In [67]:
X_csr = X_coo.tocsr()

In [68]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.intc'>'
	with 3 stored elements in Compressed Sparse Row format>

In [69]:
X_csr.indices

array([2, 2, 0])

In [70]:
X_csr.indptr

array([0, 0, 1, 2, 2, 3])

In [71]:
X_csr.data

array([1, 3, 2], dtype=int32)

In [72]:
X_csr.tocoo()

<5x5 sparse matrix of type '<class 'numpy.intc'>'
	with 3 stored elements in COOrdinate format>

You can directly load a CSR matrix from COO format:

In [73]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [74]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.intc'>'
	with 3 stored elements in Compressed Sparse Row format>

Duplicate entries are summed in CSR, not in COO:

In [75]:
row = [1, 4, 2, 1]
col = [2, 0, 2, 2]
data = [1, 2, 3, 4]

In [76]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [77]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 4 stored elements in COOrdinate format>

In [78]:
X_coo.data

array([1, 2, 3, 4])

In [79]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [80]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.intc'>'
	with 3 stored elements in Compressed Sparse Row format>

In [82]:
X_csr.data

array([5, 3, 2], dtype=int32)

## To do

* Build the following matrix in sparse CSR format:
$$
\begin{pmatrix}
0 & 0 & 1& 2\\
3 & 0& 0& 0\\
0& 0& 4& 0
\end{pmatrix}
$$

In [ ]:
indptr=[0,2,3,4]
data=[1,2,3,4]
indices=[2,3,0,2]